apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  labels: 
    app: guestbook-ui
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: "http"
  selector:
    app: guestbook-ui
